const functions = require('firebase-functions');
const admin = require('firebase-admin');
const fetch = require('node-fetch'); // requires node-fetch v2

admin.initializeApp();
const db = admin.firestore();

const toStartOfTodayYangon = () => {
  const now = new Date();
  const yangonNow = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Yangon' }));
  yangonNow.setHours(0, 0, 0, 0);
  return yangonNow;
};

const escapeMarkdown = (value = '') => String(value).replace(/([_*[\]()~`>#+\-=|{}.!])/g, '\\$1');

/**
 * Scheduled Cloud Function (Runs every day at 11:59 PM Myanmar time)
 * Sends each tenant's daily sale summary to its configured Telegram chat.
 */
exports.dailyTelegramBackup = functions.pubsub
  .schedule('59 23 * * *')
  .timeZone('Asia/Yangon')
  .onRun(async () => {
    try {
      const today = toStartOfTodayYangon();
      const todayISO = today.toISOString().slice(0, 10);

      const tenantsSnap = await db
        .collection('pos_settings')
        .where('telegramBackup', '==', true)
        .get();

      if (tenantsSnap.empty) return null;

      for (const tenantDoc of tenantsSnap.docs) {
        const tenantId = tenantDoc.id;
        const settings = tenantDoc.data();

        if (!settings.botToken || !settings.chatId) continue;

        const salesSnap = await db
          .collection('pos_records')
          .where('tenantId', '==', tenantId)
          .where('type', 'in', ['Sale', 'sale'])
          .where('date', '==', todayISO)
          .get();

        let dailyTotal = 0;
        salesSnap.forEach((doc) => {
          dailyTotal += Number(doc.data().amount || doc.data().total || 0);
        });

        const shopName = escapeMarkdown(settings.shopName || settings.storeName || tenantId);
        const message = [
          '📊 *QuickPOS Daily Summary*',
          `🏢 Store: ${shopName}`,
          `📅 Date: ${escapeMarkdown(todayISO)}`,
          '',
          `💰 Total Revenue: *${dailyTotal.toLocaleString()} MMK*`,
          `🧾 Transactions: ${salesSnap.size}`,
          '',
          '_Automated backup generated by QuickPOS\._',
        ].join('\n');

        const response = await fetch(`https://api.telegram.org/bot${settings.botToken}/sendMessage`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chat_id: settings.chatId,
            text: message,
            parse_mode: 'MarkdownV2',
          }),
        });

        if (!response.ok) {
          const body = await response.text();
          console.error(`Telegram backup failed for ${tenantId}:`, body);
        }
      }

      console.log('Daily Telegram backup executed successfully');
      return null;
    } catch (error) {
      console.error('Backup failed:', error);
      return null;
    }
  });
